Add files via upload
RV2109ATQC/CrashCourseAT2109 pull request #47
Opened 2021-09-29 18:28 UTC by Sasha380

2021-09-29 19:58 UTC, SvitlanaLN reviewed
int x = 10;
int y = 4;
int z = (x + y) / 2;
Answer z = 7.

But 
int x = 3;
int y = 4;
int z = (x + y) / 2;
Answer z=3 
It is not correct answer. Correct answer must be z=3.5.

Change your code like:
int x = 3;
int y = 4;
int z = (x + y) / 2.0 ;

or

double x = 3;
double y = 4;
double z = (x + y) / 2 ;

and you will get the right answer z=2.5

2021-09-29 20:22 UTC, Nataly997 approved these changes

2021-09-29 21:14 UTC, romanukhaav requested changes
Why do you use the same name for different requests?

2021-09-30 07:15 UTC, Iryna756 commented
You need to write in English. Use the word "task" and not the word "задача"

2021-10-03 15:39 UTC, closed without merging