Add tasks 206-208
RV2109ATQC/CrashCourseAT2109 pull request #51
Opened 2021-09-30 05:28 UTC by zaetsa12

2021-09-30 05:58 UTC, Nataly997 approved these changes

2021-09-30 06:01 UTC, FeloniukM approved these changes

2021-09-30 06:52 UTC, romanukhaav approved these changes

2021-09-30 06:52 UTC, romanukhaav commented on Projects/Team1/AnnaZaiets/Task2/Task2_2/Program.cs
> +                Console.WriteLine("Чисел" + b);
Use only English plese

2021-09-30 08:21 UTC, dazeforlife approved these changes

2021-09-30 11:45 UTC, romanukhaav requested changes
please, fix all comments

2021-09-30 11:45 UTC, romanukhaav commented on Projects/Team1/AnnaZaiets/Task2/Task2/Program.cs
> +            //Console.WriteLine($"The sum of numbers: {firstNum + secondNum + thirdNum}\nThe product of numbers: {firstNum * secondNum * thirdNum}");
Do we need this comment?

2021-09-30 11:45 UTC, romanukhaav commented on Projects/Team1/AnnaZaiets/Task2/Task2/Program.cs
> +
Try to avoid redundant empty rows

2021-09-30 12:34 UTC, Sasha380 approved these changes

2021-09-30 15:52 UTC, zaetsa12 commented on Projects/Team1/AnnaZaiets/Task2/Task2/Program.cs
> +            //Console.WriteLine($"The sum of numbers: {firstNum + secondNum + thirdNum}\nThe product of numbers: {firstNum * secondNum * thirdNum}");
no, I forgot to delete

2021-09-30 15:52 UTC, zaetsa12 commented on Projects/Team1/AnnaZaiets/Task2/Task2_2/Program.cs
> +                Console.WriteLine("Чисел" + b);
oops , ок

2021-09-30 20:35 UTC, SvitlanaLN reviewed
![image](https://user-images.githubusercontent.com/82731013/135526066-20e52c0a-2eeb-4cce-8194-2c85d2d34cbf.png)
Here you may use label or recursion to return to the beginning of the program and repeat again:

else
            {
               // Console.WriteLine("Введіть число від 0 до 100");
                Main(args);
            }

2021-10-01 11:37 UTC, zaetsa12 commented
> ![image](https://user-images.githubusercontent.com/82731013/135526066-20e52c0a-2eeb-4cce-8194-2c85d2d34cbf.png) Here you may use label or recursion to return to the beginning of the program and repeat again:
> 
> else { // Console.WriteLine("Введіть число від 0 до 100"); Main(args); }
> 
> or
> 
> else { // Console.WriteLine("Введіть число від 0 до 100"); goto label1; }

thanks for the interesting thought

2021-10-01 17:35 UTC, SvitlanaLN approved these changes

2021-10-02 17:55 UTC, romanukhaav approved these changes

2021-10-02 17:55 UTC, merged